#!/bin/sh

KV=`uname -r`
LKM_INS_DIR="/lib/modules/$KV/kernel/net/kconnp"
BIN_INS_DIR="/bin"
CFG_INS_DIR="/etc"
CFG_FILES="kconnp.conf iports.allow iports.deny"
PWD=`pwd`
mkdir -p $LKM_INS_DIR
cp -f $PWD/kconnp.ko $LKM_INS_DIR
cp --preserve=mode -f $PWD/scripts/kconnp $BIN_INS_DIR
for f in $CFG_FILES
do
if [ ! -e $CFG_INS_DIR/$f ]
then
cp $PWD/cfg-files/$f $CFG_INS_DIR
fi
done
