#!/bin/sh

help(){
    cat <<EOF
Kconnp actions:
    stats
    reload
    start
    stop
    restart
EOF
exit;
}

kv=`uname -r`;
kmconnp="/lib/modules/$kv/kernel/net/kconnp/kconnp.ko";
kconnp_cfgs="kconnp.conf iports.allow iports.deny primitives.deny";

stats(){
    cat /proc/kconnp/stats.info;
}

reload(){
    for f in $kconnp_cfgs
    do 
        cat /etc/$f > /proc/kconnp/$f;
    done;
}

start(){
    if (lsmod | grep '\bkconnp\b' > /dev/null)
    then
        echo "kconnp already running.";
        exit;
    else
        insmod $kmconnp  && reload;
    fi
}

stop(){
    if (lsmod | grep '\bkconnp\b' > /dev/null)
    then
        rmmod $kmconnp; 
    else 
        echo "kconnp not running.";
        exit;
    fi
}

restart(){
    stop;
    start;
}



if test $# -eq 0
then
    echo "Non action is passed!\n";
    help;
fi
while [ $# -gt 0 ]
do
    case "$1" in
        stats)
            stats;
            ;;
        reload)
            reload;
            ;;
        start)
            start;
            ;;
        stop)
            stop;
            ;;
        restart)
            restart;
            ;;
        *)
            echo "Unrecognized param: $1\n";
            help;
            ;;
    esac
    shift;
done
