#!/bin/sh

help(){
    cat <<EOF
Kconnp actions:
    stats
    reload
    start
    stop
    restart
EOF
exit;
}

kv=`uname -r`;
kmconnp="/lib/modules/$kv/kernel/net/kconnp/kconnp.ko"
kconnp_cfgs="kconnp.conf iports.allow iports.deny"

stats(){
    cat /proc/kconnp/stats.info
}

reload(){
    for f in $kconnp_cfgs
    do 
        cat /etc/$f > /proc/kconnp/$f
    done;
}

start(){
    insmod $kmconnp && reload;
}

stop(){
    rmmod $kmconnp; 
}

restart(){
    stop;
    start;
}



if test $# -eq 0
then
    echo "Non action is passed!\n";
    help;
fi
while [ $# -gt 0 ]
do
    case "$1" in
        stats)
            stats;
            ;;
        reload)
            reload;
            ;;
        start)
            start;
            ;;
        stop)
            stop;
            ;;
        restart)
            restart;
            ;;
        *)
            echo "Unrecognized param: $1\n";
            help;
            ;;
    esac
    shift;
done
